//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateProject.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class agentInfo
    {
        public decimal agentId { get; set; }
        public string agentName { get; set; }
        public string agentPhone { get; set; }
        public string agentWorkingPhone { get; set; }
        public string agentPhotoName { get; set; }
    }
}
