//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateProject.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class agency
    {
        public decimal agencyId { get; set; }
        public string agencytitle { get; set; }
        public string agencyAddress { get; set; }
        public string agencyPhone { get; set; }
        public string agencyRentalPhone { get; set; }
        public string agencyWebsite { get; set; }
        public string agencySmallImgName { get; set; }
        public string agencyBigImgName { get; set; }
    }
}
