//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateProject.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class realEstateOutput
    {
        public decimal listingsId { get; set; }
        public string title { get; set; }
        public Nullable<decimal> weeklyPrice { get; set; }
        public string region { get; set; }
        public string district { get; set; }
        public string suburb { get; set; }
        public string address { get; set; }
        public Nullable<decimal> bedroomCount { get; set; }
        public Nullable<decimal> carparksCount { get; set; }
        public Nullable<decimal> bathroomCount { get; set; }
        public Nullable<decimal> agencyId { get; set; }
        public Nullable<decimal> agentId { get; set; }
        public string firstImgName { get; set; }
    }
}
