//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateProject.Ef
{
    using System;
    using System.Collections.Generic;
    
    public partial class realestateImgName
    {
        public decimal realEstateImgNameId { get; set; }
        public string realEstateImgName1 { get; set; }
        public Nullable<decimal> listingsId { get; set; }
    }
}
