//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateProject.Ef
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RealEstateDBEntities : DbContext
    {
        public RealEstateDBEntities()
            : base("name=RealEstateDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<agencyInfo> agencyInfoes { get; set; }
        public virtual DbSet<agentInfo> agentInfoes { get; set; }
        public virtual DbSet<realestateImgNameOutput> realestateImgNameOutputs { get; set; }
        public virtual DbSet<realEstateInfo> realEstateInfoes { get; set; }
    }
}
